### ISSUE TITLE
1주차 진행

### ISSUE THREAD

**Issue by Kwakcena** [CodeSoom/project-react-1-Kwakcena#1]
## 1. 이 앱을 언제 사용하나요?

필요한 물건을 구입하거나 중고 물품을 판매할 때 사용합니다. 당근 마켓을 모티브로 하여 제작합니다.

## 2. 제약 조건은 무엇인가요?

- 메인 페이지에 들어가면 로그인 하지 않아도 최근에 추가 된 판매 품목을 볼 수 있어야 합니다.
- 원하는 물품을 검색해서 판매 글을 확인할 수 있어야 합니다.
- 카테고리별로 판매 품목을 분류해서 볼 수 있어야 합니다.
- 판매 품목을 클릭하면 자세한 정보를 볼 수 있어야 합니다.
- 로그인하면 판매자와 채팅을 통해 거래할 수 있어야 합니다.
- 채팅을 통해 거래 예약이 잡히면 판매자는 `예약중` 상태로 바꿀 수 있습니다.
- 거래가 완료되면 `판매 완료` 상태로 바꿀 수 있습니다.

## 3. 구체적인 사례는 무엇인가요?

- 사용자가 접속하면 구매하고 싶은 목록을 검색합니다.
- 원하는 품목이 있는지 확인합니다.
- 품목이 있으면 로그인 후 판매 품목을 클릭하여 자세히 확인할 수 있습니다.
- 확인 후 구매하고 싶으면 채팅을 요청하여 판매자와 채팅할 수 있습니다.
- 거래를 예약하면 판매자는 `예약 중` 상태로 바꿉니다.
- 거래가 완료되면 `판매 완료` 상태로 바꿉니다.

## 4. 이번주에 구현 할 기능을 우선 순위대로 작성해주세요.

- [X]  개발 환경 세팅 #2 #3 
- [ ]  메인 페이지 구현
    - [X]  판매 품목 렌더링 #4 
    - [X]  판매 품목 카드 리스트 형태의 UI로 렌더링 #5 
    - [ ]  카테고리에 따라 다른 판매 품목 렌더링

**Comment by hannut91** [comment]
기능이 상당히 자세하네요 ㅎㅎ 구현 할 기능들을 사용자 입장에서 기술해보는 것도 도움이 많이 됩니다.

이번주 까지는 사용자가(제가, 혹은 다른 수강생들이) 제품 품목 목록을 볼 수 있고 품목이나 카테고리로 분류해볼 수 있겠군요!

**Comment by wholemann** [comment]
이번주에 당장 써야한다면 어떤 걸 먼저 구현해야 할까요?ㅎㅎ

카테고리 구분도 필요 없이 모든 물건을 보여주는 것도 괜찮을 겁니다.

처음부터 복잡도를 높이지 않는 게 좋아보여요.

이번주에 메인페이지만 구현하면 당장 쓸 수 있는 서비스가 아닐 듯 합니다.

상세 페이지는 notion으로 대체하고 메인 페이지에서도 일정에 맞게 최소한만 구현하는 방법도 있습니다.

일단 피드백을 받으려면 매주 완성된 형태를 지향해보세요!
