### ISSUE TITLE
4주차 진행

### ISSUE THREAD

**Issue by Kwakcena** [CodeSoom/project-react-1-Kwakcena#15]
# 4주차 진행
한달 전 프로젝트를 잠시 멈췄습니다. 프로젝트의 주제가 마음에 안들기도 했고, backend 부분의 기술이 많이 필요한 주제가 아니었나 싶어서 프로젝트를 끈기있게 완성하지 못하고 잠시 놓아버렸네요. 그 동안 코딩테스트며 자기소개서며 이런저런 이유로 미루어왔는데, 다시 시작해서 어떻게든 완성해보려 합니다. 

지금까지는 `json-server` 를 이용해서 가짜 데이터를 만들고, 상품을 요청하도록 하였는데, 이를 `firebase`를 이용하도록 바꾸려고 합니다.

## 해야 할 것.
- [X] firebase 사용을 위한 initialization #16 
- [X] firebase를 이용하여 로그인 시스템 구현하기
    - [X] 사용자는 email과 password를 이용해서 로그인 할 수 있다. #17 
    - [X] 사용자는 email과 password를 이용해서 회원가입 할 수 있다. #18 
    - [X] 사용자는 gmail 을 이용하여 로그인 할 수 있다. #19
