### ISSUE TITLE
5주차 진행

### ISSUE THREAD

**Issue by Kwakcena** [CodeSoom/project-react-1-Kwakcena#20]
# 5주차 진행
- [X] 새로고침 이후에도 로그인 상태가 유지된다.
    - [ ] issue : #22 , PR : #21 
- [X] 회원가입, 로그인 후 홈 페이지로 이동한다. 
    - [X] 리덕스에서 history를 사용하기 위해 connected-react-router 라이브러리 적용 #24 
    - [X] Redirect 기능 적용 #25 
- [X] reducer 파일을 나누기 #26
