### ISSUE TITLE
6주차 진행

### ISSUE THREAD

**Issue by Kwakcena** [CodeSoom/project-react-1-Kwakcena#27]
# 6주차 진행

이번 주에는 판매글을 작성할 수 있는 컴포넌트를 만들고, firebase에 올리는 기능을 만들어 본다.

- [X] 로그인한 사용자가 판매 게시글을 올릴 수 있다.
    - [X] 사용자가 로그인하면 '판매하기' 버튼을 헤더에서 볼 수 있다. 
- [X] 판매 게시글은 firebase의 firestore에 올릴 수 있다.
    - [X] 판매 글 중 제목, 본문, 지역, 가격에 대한 글을 올릴 수 있음 #31 
    - [X] react dropzone을 이용해서 사진도 올릴 수 있도록 한다. #36 #37
    - [X] 올리려고 했던 사진을 클릭하여 다시 취소할 수 있다. #40
